<?
	$phpgw_baseline = array(
	'egw_alix_acl' => array(
		'fd' => array(
			'CURRENTAPP' => array('type' => 'varchar','precision' => '15','nullable' => False),
			'USERID' => array('type' => 'varchar','precision' => '100','nullable' => False),
			'SITEID' => array('type' => 'varchar','precision' => '10','nullable' => False),
			'PROFILEID' => array('type' => 'varchar','precision' => '10','nullable' => False),
			'DEFAULTPROFILE' => array('type' => 'varchar','precision' => '1','nullable' => False),
		),
		'pk' => array('CURRENTAPP','USERID','SITEID'),
		'fk' => array(),
		'ix' => array(),
		'uc' => array()
		),
	'egw_alix_deviations' => array(
		'fd' => array(
			'DEVIATIONID' => array('type' => 'auto','nullable' => False),
      'SEOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'SERK' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'FRMOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'FRMRK' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'IGOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'IGRK' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'ITEMOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'ITEMTITLE' => array('type' => 'longtext'),
      'CURRENTAPP' => array('type' => 'varchar','precision' => '20','nullable' => False),
			'DESCRIPTION' => array('type' => 'longtext'),
      'BYWHO' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'BYWHOGROUP' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'UPDATEDT' => array('type' => 'datetime'),
      'SUBJKEY' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'SITEID' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'ISLAST' => array('type' => 'varchar','precision' => '1','nullable' => False),
      'STATUS' => array('type' => 'varchar','precision' => '1','nullable' => False),
		),
		'pk' => array('DEVIATIONID'),
		'fk' => array(),
		'ix' => array(),
		'uc' => array()
		),		
	'egw_alix_export' => array(
		'fd' => array(
			'EXPORTID' => array('type' => 'auto','nullable' => False),
			'EXPORTNAME' => array('type' => 'varchar','precision' => '200','nullable' => False),
			'EXPORTTYPE' => array('type' => 'varchar','precision' => '100','nullable' => False),
			'EXPORTDATE' => array('type' => 'datetime'),
      'EXPORTPASSWORD' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'EXPORTUSER' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'CURRENTAPP' => array('type' => 'varchar','precision' => '20','nullable' => False),
      'EXPORTPATH' => array('type' => 'varchar','precision' => '255','nullable' => False),
		),
		'pk' => array('EXPORTID'),
		'fk' => array(),
		'ix' => array(),
		'uc' => array()
		),
	'egw_alix_import' => array(
		'fd' => array(
			'IMPORTID' => array('type' => 'auto','nullable' => False),
			'IMPORTDATE' => array('type' => 'datetime'),
      'IMPORTUSER' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'IMPORTSTATUS' => array('type' => 'varchar','precision' => '10','nullable' => False),
			'ERRORCOUNT' => array('type' => 'int','precision' => '11','nullable' => False),
			'EXPORTFILE' => array('type' => 'varchar','precision' => '200','nullable' => False),
			'REPORTFILE' => array('type' => 'varchar','precision' => '200','nullable' => False),
      'EXPORTTYPE' => array('type' => 'varchar','precision' => '100','nullable' => False),
      'CURRENTAPP' => array('type' => 'varchar','precision' => '20','nullable' => False),
      'EXPORTPATH' => array('type' => 'varchar','precision' => '255','nullable' => False),
		),
		'pk' => array('EXPORTID'),
		'fk' => array(),
		'ix' => array(),
		'uc' => array()
		),
	'egw_alix_lock' => array(
		'fd' => array(
			'ID' => array('type' => 'auto','nullable' => False),
			'STUDY' => array('type' => 'varchar','precision' => '30','nullable' => False),
			'STARTTIME' => array('type' => 'int','precision' => '12','nullable' => False),
			'STOPTIME' => array('type' => 'int','precision' => '12','nullable' => False),
			'WAITTIME' => array('type' => 'float','nullable' => False),
			'LOCKDT' => array('type' => 'datetime','nullable' => False),
			'WHO' => array('type' => 'varchar','precision' => '100','nullable' => False),
		),
		'pk' => array('ID'),
		'fk' => array(),
		'ix' => array(),
		'uc' => array()
		),
	'egw_alix_postit' => array(
		'fd' => array(
			'POSTITID' => array('type' => 'int','precision' => '11','nullable' => False),
      'SEOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'SERK' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'FRMOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'FRMRK' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'IGOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'IGRK' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'CURRENTAPP' => array('type' => 'varchar','precision' => '20','nullable' => False),
			'TXT' => array('type' => 'longtext'),
      'BYWHO' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'BYWHOGROUP' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'ITEMOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'SUBJKEY' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'SITEID' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'DT' => array('type' => 'datetime'),
      'ISREAD' => array('type' => 'varchar','precision' => '1','nullable' => False),
		),
		'pk' => array('SEOID','SERK','FRMOID','FRMRK','IGOID','IGRK','CURRENTAPP','ITEMOID','SUBJKEY'),
		'fk' => array(),
		'ix' => array(),
		'uc' => array()
		),		
	'egw_alix_queries' => array(
		'fd' => array(
			'QUERYID' => array('type' => 'auto','nullable' => False),
      'SEOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'SERK' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'FRMOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'FRMRK' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'IGOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'IGRK' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'POSITION' => array('type' => 'int','precision' => '2','nullable' => False),
      'CURRENTAPP' => array('type' => 'varchar','precision' => '20','nullable' => False),
			'DESCRIPTION' => array('type' => 'longtext'),
      'ITEMTITLE' => array('type' => 'longtext'),
      'ISMANUAL' => array('type' => 'varchar','precision' => '1','nullable' => False),
      'BYWHO' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'BYWHOGROUP' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'UPDATEDT' => array('type' => 'datetime'),
      'QUERYTYPE' => array('type' => 'varchar','precision' => '2','nullable' => False),
      'QUERYSTATUS' => array('type' => 'varchar','precision' => '1','nullable' => False),
      'ANSWER' => array('type' => 'longtext'),
      'ITEMOID' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'SUBJKEY' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'SITEID' => array('type' => 'varchar','precision' => '10','nullable' => False),
      'ISLAST' => array('type' => 'varchar','precision' => '1','nullable' => False),
      'VALUE' => array('type' => 'varchar','precision' => '255','nullable' => False),
      'DECODE' => array('type' => 'longtext'),
      'CONTEXTKEY' => array('type' => 'longtext'),      
		),
		'pk' => array('QUERYID'),
		'fk' => array(),
		'ix' => array(),
		'uc' => array()
		),    
	'egw_alix_sites' => array(
		'fd' => array(
			'SITEID' => array('type' => 'varchar','precision' => '10','nullable' => False),
			'SITENAME' => array('type' => 'varchar','precision' => '50','nullable' => False),
      'CURRENTAPP' => array('type' => 'varchar','precision' => '15','nullable' => False),
      'COUNTRY' => array('type' => 'varchar','precision' => '100','nullable' => False),
		),
		'pk' => array('SITEID','CURRENTAPP'),
		'fk' => array(),
		'ix' => array(),
		'uc' => array()
		),
	);
?>